// code-trace: steps generated by really executing the code (shared/visuals/tracer.js).
import { IssueList, bindCaptions, checkCaptions, checkEnum, isInt, isPlainObject, nonEmpty, renderText } from '../common.js';

export const schema = {
  kind: 'code-trace',
  summary: 'Code with the current line highlighted, variables by scope (closures visible as captured scopes), call stack, heap and console. Steps come from real execution.',
  fields: {
    file: 'string — path of the JavaScript file relative to the lesson directory (or use "code")',
    code: 'string — inline JavaScript source (alternative to "file")',
    steps: '"captioned" (default: only captioned steps are shown) | "all" (every generated step is shown and must have a caption)',
    maxSteps: 'integer — step cap for the tracer (default 400)',
    allowError: 'boolean — accept a program that throws (default true; the throw becomes the last step)',
    allowTruncated: 'boolean — accept a trace cut at maxSteps (default false)',
    captions: '[{ at: { line, hit?: n | "every", kind?: stmt|cond|iter|update|call|return|throw|await|resume|end } | { step: n }, text: { uk, en } }]',
  },
};

export function validate(spec, issues = new IssueList()) {
  if (!isPlainObject(spec)) { issues.add('spec', 'must be a mapping'); return issues; }
  if (!nonEmpty(spec.file) && !nonEmpty(spec.code)) issues.add('spec.file', 'needs "file" (path relative to the lesson directory) or inline "code"');
  if (nonEmpty(spec.file) && nonEmpty(spec.code)) issues.add('spec', 'use either "file" or "code", not both');
  if (nonEmpty(spec.file) && !/\.(m?js)$/.test(spec.file)) issues.add('spec.file', 'the traced file must be plain JavaScript (.js / .mjs)');
  checkEnum(issues, spec.steps, 'spec.steps', ['captioned', 'all'], { optional: true });
  if (spec.maxSteps !== undefined && !(isInt(spec.maxSteps) && spec.maxSteps >= 2 && spec.maxSteps <= 2000)) issues.add('spec.maxSteps', 'must be an integer between 2 and 2000');
  checkCaptions(issues, spec.captions, 'spec.captions');
  if (nonEmpty(spec.code) && /^\s*(import|export)\b/m.test(spec.code)) issues.add('spec.code', 'import/export are not supported in a traced file: keep the example self-contained');
  return issues;
}

/** Run the tracer and return the raw trace (also used by memory-graph `from: trace`). */
export async function runTrace(spec, ctx) {
  const { traceSource } = await import('../tracer.js');
  const file = nonEmpty(spec.file) ? spec.file : 'example.js';
  const source = nonEmpty(spec.code) ? spec.code : await ctx.readFile(spec.file);
  return { file, source, result: await traceSource(source, { file: file.split('/').pop(), maxSteps: spec.maxSteps ?? 400 }) };
}

export async function compile(spec, ctx, issues = new IssueList()) {
  validate(spec, issues);
  if (!issues.ok) return { spec: null, issues };
  let run;
  try {
    run = await runTrace(spec, ctx);
  } catch (error) {
    issues.add('spec.file', `cannot read "${spec.file}": ${error.message}`);
    return { spec: null, issues };
  }
  const { file, source, result } = run;
  if (/^\s*(import|export)\b/m.test(source)) issues.add('spec.file', 'import/export are not supported in a traced file: keep the example self-contained');
  if (result.error && result.error.phase === 'compile') {
    issues.add('spec.file', `syntax error in ${file}${result.error.line ? ` at line ${result.error.line}` : ''}: ${result.error.message}`);
    return { spec: null, issues };
  }
  const trace = result.trace;
  if (result.error && spec.allowError === false) issues.add('spec.file', `the program throws ${result.error.name}: ${result.error.message} (set allowError: true if that is the point of the example)`);
  if (trace.truncated && spec.allowTruncated !== true) issues.add('spec.maxSteps', `the trace was cut at ${trace.maxSteps} steps; shorten the example or raise maxSteps (set allowTruncated: true to accept a cut trace)`);
  if (trace.steps.length === 0) { issues.add('spec.file', 'the program produced no steps (is the file empty?)'); return { spec: null, issues }; }
  return { spec: buildSpec(spec, ctx, issues, { file, source, trace }), issues };
}

/** Build the compiled spec from a raw trace. Exported for memory-graph (from: trace). */
export function buildSpec(spec, ctx, issues, { file, source, trace }) {
  const mode = spec.steps ?? 'captioned';
  const byStep = bindCaptions(issues, spec.captions, trace.steps, 'spec.captions');
  const visible = [];
  trace.steps.forEach((raw, i) => {
    const ci = byStep.get(i);
    if (ci === undefined) {
      if (mode === 'all') issues.add('spec.captions', `step ${i + 1} (line ${raw.line}, ${raw.kind}) has no caption; every shown step needs one (use hit: "every" for repeated lines or steps: captioned)`);
      return;
    }
    visible.push({ raw, caption: renderText(ctx, spec.captions[ci].text) });
  });
  if (visible.length === 0) issues.add('spec.captions', 'no caption matched a generated step');
  const consoleEntries = trace.console.map((e) => ({ level: e.level, text: e.text }));
  return {
    kind: 'code-trace',
    file,
    code: source,
    language: 'js',
    mode,
    totalSteps: trace.steps.length,
    truncated: trace.truncated,
    error: trace.error ?? null,
    console: consoleEntries,
    steps: visible.map(({ raw, caption }) => ({ caption, trace: raw, logged: trace.console.filter((e) => e.step < raw.i || (raw.kind === 'end' && e.step <= raw.i)).length })),
  };
}

/**
 * Wrap a run-time trace (sandbox `trace` event) in the compiled shape so the same player renders it.
 * `source` is the code of `file`, or a map path → code of every traced file (a project with several
 * modules): the player then shows the file of each step (step.file).
 */
export function traceToSpec(trace, source, file = 'index.js') {
  const consoleEntries = (trace.console ?? []).map((e) => ({ level: e.level, text: e.text }));
  const files = source !== null && typeof source === 'object' ? source : null;
  return {
    kind: 'code-trace',
    file,
    code: files ? files[file] ?? '' : source,
    ...(files ? { files } : {}),
    language: 'js',
    mode: 'all',
    totalSteps: trace.steps.length,
    truncated: trace.truncated === true,
    maxSteps: trace.maxSteps ?? null,
    error: trace.error ?? null,
    console: consoleEntries,
    steps: trace.steps.map((raw) => ({ caption: null, trace: raw, logged: (trace.console ?? []).filter((e) => e.step < raw.i || (raw.kind === 'end' && e.step <= raw.i)).length })),
  };
}
