// Creates the planner lab project 1.3.0 in ./no12-lab — run it from ~/js-course.
// It never overwrites: if ./no12-lab already exists, it stops and changes nothing.
import { existsSync } from 'node:fs';
import { mkdir, writeFile } from 'node:fs/promises';
import path from 'node:path';

const files = {
  "package.json": "{\n  \"name\": \"no12-lab\",\n  \"version\": \"1.3.0\",\n  \"private\": true,\n  \"type\": \"module\",\n  \"scripts\": {\n    \"lint\": \"eslint .\",\n    \"typecheck\": \"tsc -p .\",\n    \"test\": \"node --test test/app.test.ts\",\n    \"build\": \"node scripts/build.mjs\",\n    \"ci\": \"node scripts/ci.mjs\"\n  }\n}\n",
  "tsconfig.json": "{\n  \"compilerOptions\": {\n    \"target\": \"es2023\",\n    \"module\": \"nodenext\",\n    \"strict\": true,\n    \"noEmit\": true,\n    \"allowImportingTsExtensions\": true,\n    \"verbatimModuleSyntax\": true,\n    \"erasableSyntaxOnly\": true,\n    \"types\": [\"node\"],\n    \"skipLibCheck\": true\n  },\n  \"include\": [\"src\", \"test\"]\n}\n",
  "eslint.config.js": "// ESLint: the recommended JavaScript rules plus typescript-eslint's recommended rules for .ts files.\nimport js from '@eslint/js';\nimport tseslint from 'typescript-eslint';\n\nexport default tseslint.config(\n  { ignores: ['release/', 'artifacts/', 'node_modules/'] },\n  js.configs.recommended,\n  ...tseslint.configs.recommended,\n  { files: ['scripts/**/*.mjs'], languageOptions: { globals: { console: 'readonly', process: 'readonly' } } },\n);\n",
  ".gitignore": "node_modules/\nrelease/\nartifacts/\ndata/\n",
  "src/tasks.ts": "export type Priority = 'low' | 'normal' | 'high';\nexport type Task = { id: string; title: string; dueDate: string | null; done: boolean; priority: Priority };\n\nexport const fixtures: Task[] = [\n  { id: 't-01', title: '%%plants%%', dueDate: '2026-03-02', done: false, priority: 'normal' },\n  { id: 't-02', title: '%%books%%', dueDate: '2026-03-01', done: false, priority: 'high' },\n  { id: 't-03', title: '%%grandma%%', dueDate: null, done: false, priority: 'low' },\n  { id: 't-04', title: '%%internet%%', dueDate: '2026-02-27', done: true, priority: 'high' },\n];\n\nconst rank: Record<Priority, number> = { high: 0, normal: 1, low: 2 };\n\n// High priority first; inside one priority, the earlier due date first (no date last).\nexport function byPriority(a: Task, b: Task): number {\n  return rank[a.priority] - rank[b.priority] || (a.dueDate ?? '9999').localeCompare(b.dueDate ?? '9999');\n}\n",
  "src/config.ts": "// Reads the configuration once, at startup.\nimport path from 'node:path';\n\nexport type Config = Readonly<{ port: number; host: string; dataDir: string }>;\n\nexport function loadConfig(env: NodeJS.ProcessEnv): Config {\n  const problems: string[] = [];\n  const port = Number(env.PORT ?? '7330');\n  if (!/^\\d+$/.test(env.PORT ?? '7330') || port < 1 || port > 65535) problems.push(`PORT is not a port: \"${env.PORT}\"`);\n  const host = env.HOST ?? '127.0.0.1';\n  if (host !== '127.0.0.1' && host !== '::1') problems.push(`HOST must be loopback: \"${host}\"`);\n  const dataDir = env.DATA_DIR ?? '';\n  if (!path.isAbsolute(dataDir)) problems.push(`DATA_DIR must be an absolute path: \"${dataDir}\"`);\n  if (problems.length > 0) throw new Error(problems.join('\\n'));\n  return Object.freeze({ port, host, dataDir });\n}\n",
  "src/store.ts": "// The task store: one JSON file in DATA_DIR, replaced atomically (temp file + rename, as in NO-02).\nimport { mkdir, readFile, rename, writeFile } from 'node:fs/promises';\nimport path from 'node:path';\nimport { fixtures, type Task } from './tasks.ts';\n\nexport type Store = { list(): Task[]; add(task: Task): Promise<void> };\n\nexport async function openStore(dataDir: string): Promise<Store> {\n  const file = path.join(dataDir, 'tasks.json');\n  await mkdir(dataDir, { recursive: true });\n  let tasks: Task[];\n  try {\n    tasks = JSON.parse(await readFile(file, 'utf8')).records;\n  } catch {\n    tasks = structuredClone(fixtures);\n  }\n  const save = async () => {\n    await writeFile(`${file}.tmp`, JSON.stringify({ schemaVersion: 1, records: tasks }));\n    await rename(`${file}.tmp`, file);\n  };\n  await save();\n  return {\n    list: () => tasks,\n    async add(task) {\n      tasks.push(task);\n      await save();\n    },\n  };\n}\n",
  "src/app.ts": "// The planner HTTP API: GET /tasks (sorted by priority), POST /tasks and GET /metrics.\nimport http from 'node:http';\nimport { randomUUID } from 'node:crypto';\nimport { byPriority, type Task } from './tasks.ts';\nimport type { Store } from './store.ts';\n\nexport function createApp(store: Store): http.Server {\n  const counts = new Map<string, number>();\n  const count = (key: string) => counts.set(key, (counts.get(key) ?? 0) + 1);\n\n  return http.createServer(async (request, response) => {\n    const send = (status: number, body: unknown, type = 'application/json') => {\n      count(`${request.method} ${request.url} ${status}`);\n      response.writeHead(status, { 'content-type': type });\n      response.end(type === 'application/json' ? JSON.stringify(body) : String(body));\n    };\n    if (request.method === 'GET' && request.url === '/tasks') return send(200, store.list().toSorted(byPriority));\n    if (request.method === 'POST' && request.url === '/tasks') {\n      let text = '';\n      for await (const chunk of request) text += chunk;\n      const input = JSON.parse(text || '{}');\n      if (typeof input.title !== 'string' || input.title.trim() === '') return send(400, { error: 'title is required' });\n      const task: Task = { id: randomUUID(), title: input.title.trim(), dueDate: input.dueDate ?? null, done: false, priority: input.priority ?? 'normal' };\n      await store.add(task);\n      return send(201, task);\n    }\n    if (request.method === 'GET' && request.url === '/metrics') {\n      const lines = [...counts].map(([key, n]) => `http_requests_total{request=\"${key}\"} ${n}`);\n      return send(200, lines.join('\\n') + '\\n', 'text/plain; charset=utf-8');\n    }\n    return send(404, { error: 'not found' });\n  });\n}\n",
  "src/server.ts": "// Starts the planner service: configuration first, then the store, then listen().\nimport { createApp } from './app.ts';\nimport { loadConfig } from './config.ts';\nimport { openStore } from './store.ts';\n\nlet config;\ntry {\n  config = loadConfig(process.env);\n} catch (error) {\n  console.error(`Invalid configuration:\\n${(error as Error).message}`);\n  process.exit(1);\n}\nconst server = createApp(await openStore(config.dataDir));\nserver.listen(config.port, config.host, () => {\n  console.log(`planner ${process.env.npm_package_version ?? ''} listening on http://${config.host}:${config.port}`);\n});\nprocess.on('SIGINT', () => server.close(() => console.log('Server closed.')));\n",
  "test/app.test.ts": "// Real-HTTP tests of the planner API, each with its own temp data directory.\nimport assert from 'node:assert/strict';\nimport { mkdtemp, rm } from 'node:fs/promises';\nimport { tmpdir } from 'node:os';\nimport path from 'node:path';\nimport { test } from 'node:test';\nimport { createApp } from '../src/app.ts';\nimport { openStore } from '../src/store.ts';\n\nasync function start(t: { after(fn: () => unknown): void }) {\n  const dir = await mkdtemp(path.join(tmpdir(), 'no12-lab-'));\n  const server = createApp(await openStore(dir));\n  await new Promise<void>((resolve) => server.listen(0, '127.0.0.1', resolve));\n  t.after(async () => {\n    server.close();\n    await rm(dir, { recursive: true, force: true });\n  });\n  const { port } = server.address() as { port: number };\n  return `http://127.0.0.1:${port}`;\n}\n\ntest('GET /tasks lists high priority first', async (t) => {\n  const base = await start(t);\n  const tasks = await (await fetch(`${base}/tasks`)).json();\n  assert.deepEqual(tasks.map((task: { id: string }) => task.id), ['t-04', 't-02', 't-01', 't-03']);\n});\n\ntest('POST /tasks stores a task', async (t) => {\n  const base = await start(t);\n  const response = await fetch(`${base}/tasks`, { method: 'POST', body: JSON.stringify({ title: '%%dentist%%', priority: 'normal' }) });\n  assert.equal(response.status, 201);\n  const tasks = await (await fetch(`${base}/tasks`)).json();\n  assert.equal(tasks.length, 5);\n});\n",
  "scripts/build.mjs": "// Builds release/: plain JavaScript from src/*.ts plus its own package.json, ready for `npm pack`.\nimport { mkdir, readdir, readFile, rm, writeFile } from 'node:fs/promises';\nimport { stripTypeScriptTypes } from 'node:module';\n\nconst pkg = JSON.parse(await readFile('package.json', 'utf8'));\nawait rm('release', { recursive: true, force: true });\nawait mkdir('release');\nfor (const name of await readdir('src')) {\n  const code = stripTypeScriptTypes(await readFile(`src/${name}`, 'utf8')).replace(/(from\\s+'\\.\\/[\\w-]+)\\.ts'/g, \"$1.js'\");\n  await writeFile(`release/${name.replace(/\\.ts$/, '.js')}`, code);\n}\nconst manifest = { name: pkg.name, version: pkg.version, private: true, type: 'module', main: 'server.js', engines: { node: '>=22.13' } };\nawait writeFile('release/package.json', JSON.stringify(manifest, null, 2) + '\\n');\nconsole.log(`build: release/ holds ${(await readdir('release')).length} files of ${pkg.name} ${pkg.version}`);\n",
  "scripts/ci.mjs": "// The local CI: the same ordered checks a CI service would run, stopping at the first failure.\n// A passing run leaves exactly one artifact (an npm pack tarball) and a release record next to it.\nimport { spawnSync } from 'node:child_process';\nimport { createHash } from 'node:crypto';\nimport { mkdir, readFile, writeFile } from 'node:fs/promises';\n\nconst stages = [\n  ['install', 'npm ci --no-audit --no-fund'],\n  ['lint', 'npx eslint .'],\n  ['typecheck', 'npx tsc -p .'],\n  ['test', 'node --test test/app.test.ts'],\n  ['build', 'node scripts/build.mjs'],\n];\nfor (const [name, command] of stages) {\n  console.log(`\\n▶ ${name}: ${command}`);\n  const result = spawnSync(command, { shell: true, stdio: 'inherit' });\n  if (result.status !== 0) {\n    console.error(`\\n✖ CI stopped at \"${name}\" (exit code ${result.status}). No artifact was produced.`);\n    process.exit(1);\n  }\n}\n\nconst pkg = JSON.parse(await readFile('package.json', 'utf8'));\nawait mkdir('artifacts', { recursive: true });\nconst packed = spawnSync('npm pack ./release --pack-destination artifacts --silent', { shell: true, encoding: 'utf8' });\nif (packed.status !== 0) {\n  console.error(packed.stderr);\n  process.exit(1);\n}\nconst file = `artifacts/${packed.stdout.trim().split('\\n').pop()}`;\nconst sha256 = createHash('sha256').update(await readFile(file)).digest('hex');\nconst commit = spawnSync('git rev-parse --short HEAD', { shell: true, encoding: 'utf8' }).stdout.trim() || 'not a git repository';\nconst record = { name: pkg.name, version: pkg.version, commit, node: process.version, artifact: file, sha256 };\nawait writeFile(`artifacts/${pkg.name}-${pkg.version}.release.json`, JSON.stringify(record, null, 2) + '\\n');\nconsole.log(`\\n✔ CI passed: ${file}\\n  sha256 ${sha256}`);\n"
};

if (existsSync('no12-lab')) {
  console.error('no12-lab already exists here; nothing was changed.');
  process.exitCode = 1;
} else {
  for (const [name, text] of Object.entries(files)) {
    await mkdir(path.dirname(path.join('no12-lab', name)), { recursive: true });
    await writeFile(path.join('no12-lab', name), text);
  }
  console.log(`Created no12-lab with ${Object.keys(files).length} files.`);
}
