// Upgrades the planner lab project from 1.3.0 to 1.4.0: health checks, metrics, a graceful
// shutdown and a load script. Run it inside ~/js-course/no12-lab. It refuses to run anywhere else,
// on another version, or when git shows uncommitted changes (so that nothing of yours is overwritten).
import { execSync } from 'node:child_process';
import { readFileSync, writeFileSync } from 'node:fs';

const files = {
  "eslint.config.js": "// ESLint: the recommended JavaScript rules plus typescript-eslint's recommended rules for .ts files.\nimport js from '@eslint/js';\nimport tseslint from 'typescript-eslint';\n\nexport default tseslint.config(\n  { ignores: ['release/', 'artifacts/', 'node_modules/'] },\n  js.configs.recommended,\n  ...tseslint.configs.recommended,\n  {\n    files: ['scripts/**/*.mjs'],\n    languageOptions: {\n      globals: { console: 'readonly', process: 'readonly', fetch: 'readonly', performance: 'readonly', AbortSignal: 'readonly', setTimeout: 'readonly' },\n    },\n  },\n);\n",
  "src/store.ts": "// The task store: one JSON file in DATA_DIR, replaced atomically (temp file + rename, as in NO-02).\n// Saves run one after another (as in NO-05): two concurrent saves of one temp file would collide.\nimport { mkdir, readFile, rename, writeFile } from 'node:fs/promises';\nimport path from 'node:path';\nimport { fixtures, type Task } from './tasks.ts';\n\nexport type Store = { list(): Task[]; add(task: Task): Promise<void> };\n\nexport async function openStore(dataDir: string): Promise<Store> {\n  const file = path.join(dataDir, 'tasks.json');\n  await mkdir(dataDir, { recursive: true });\n  let tasks: Task[];\n  try {\n    tasks = JSON.parse(await readFile(file, 'utf8')).records;\n  } catch {\n    tasks = structuredClone(fixtures);\n  }\n  let queue: Promise<void> = Promise.resolve();\n  const save = () => {\n    queue = queue.then(async () => {\n      await writeFile(`${file}.tmp`, JSON.stringify({ schemaVersion: 1, records: tasks }));\n      await rename(`${file}.tmp`, file);\n    });\n    return queue;\n  };\n  await save();\n  return {\n    list: () => tasks,\n    async add(task) {\n      tasks.push(task);\n      await save();\n    },\n  };\n}\n",
  "src/metrics.ts": "// Request metrics: a counter per route and status, and latency percentiles per route.\nimport { createHistogram, type RecordableHistogram } from 'node:perf_hooks';\n\nexport type Metrics = { record(route: string, status: number, ms: number): void; text(): string };\n\nexport function createMetrics(): Metrics {\n  const requests = new Map<string, number>();\n  const latency = new Map<string, RecordableHistogram>();\n  return {\n    record(route, status, ms) {\n      const key = `${route} ${status}`;\n      requests.set(key, (requests.get(key) ?? 0) + 1);\n      if (!latency.has(route)) latency.set(route, createHistogram());\n      latency.get(route)!.record(Math.max(1, Math.round(ms * 1000)));\n    },\n    text() {\n      const lines: string[] = [];\n      for (const [key, count] of requests) {\n        const [route, status] = key.split(' ');\n        lines.push(`http_requests_total{route=\"${route}\",status=\"${status}\"} ${count}`);\n      }\n      for (const [route, histogram] of latency) {\n        for (const q of [50, 95]) lines.push(`http_request_duration_ms{route=\"${route}\",quantile=\"${q / 100}\"} ${(histogram.percentile(q) / 1000).toFixed(1)}`);\n      }\n      return lines.join('\\n') + '\\n';\n    },\n  };\n}\n",
  "src/app.ts": "// The planner HTTP API: tasks, health checks and metrics.\nimport http from 'node:http';\nimport { randomUUID } from 'node:crypto';\nimport { byPriority, type Task } from './tasks.ts';\nimport type { Store } from './store.ts';\nimport { createMetrics } from './metrics.ts';\n\nexport type Health = { shuttingDown: boolean };\n\nexport function createApp(store: Store, health: Health = { shuttingDown: false }): http.Server {\n  const metrics = createMetrics();\n\n  return http.createServer(async (request, response) => {\n    const started = performance.now();\n    const route = (request.url ?? '/').split('?')[0];\n    const send = (status: number, body: unknown, type = 'application/json') => {\n      const headers: Record<string, string> = { 'content-type': type };\n      if (health.shuttingDown) headers.connection = 'close';\n      response.writeHead(status, headers);\n      response.end(type === 'application/json' ? JSON.stringify(body) : String(body));\n      metrics.record(route, status, performance.now() - started);\n    };\n    try {\n      if (route === '/livez') return send(200, { status: 'alive' });\n      if (route === '/readyz') return health.shuttingDown ? send(503, { status: 'shutting down' }) : send(200, { status: 'ready' });\n      if (route === '/metrics') return send(200, metrics.text(), 'text/plain; charset=utf-8');\n      if (request.method === 'GET' && route === '/tasks') return send(200, store.list().toSorted(byPriority));\n      if (request.method === 'POST' && route === '/tasks') {\n        let text = '';\n        for await (const chunk of request) text += chunk;\n        const input = JSON.parse(text || '{}');\n        if (typeof input.title !== 'string' || input.title.trim() === '') return send(400, { error: 'title is required' });\n        const task: Task = { id: randomUUID(), title: input.title.trim(), dueDate: input.dueDate ?? null, done: false, priority: input.priority ?? 'normal' };\n        await store.add(task);\n        return send(201, task);\n      }\n      return send(404, { error: 'not found' });\n    } catch {\n      return send(500, { error: 'internal error' });\n    }\n  });\n}\n",
  "src/server.ts": "// Starts the planner service: configuration, store, listen() — and a graceful shutdown on\n// SIGTERM or SIGINT: stop accepting, let requests in flight finish (at most 5 s), then exit.\nimport { readFileSync } from 'node:fs';\nimport { createApp, type Health } from './app.ts';\nimport { loadConfig } from './config.ts';\nimport { openStore } from './store.ts';\n\nconst { version } = JSON.parse(readFileSync(new URL('./package.json', import.meta.url), 'utf8'));\nlet config;\ntry {\n  config = loadConfig(process.env);\n} catch (error) {\n  console.error(`Invalid configuration:\\n${(error as Error).message}`);\n  process.exit(1);\n}\nconst health: Health = { shuttingDown: false };\nconst server = createApp(await openStore(config.dataDir), health);\nserver.listen(config.port, config.host, () => {\n  console.log(`planner ${version} (pid ${process.pid}, NODE_ENV=${process.env.NODE_ENV ?? ''}) listening on http://${config.host}:${config.port}`);\n});\n\nfunction shutdown(signal: string) {\n  if (health.shuttingDown) return;\n  health.shuttingDown = true;\n  console.log(`${signal}: draining requests in flight (deadline 5000 ms)`);\n  const deadline = setTimeout(() => {\n    console.error('deadline passed: cutting connections');\n    server.closeAllConnections();\n    process.exit(1);\n  }, 5000);\n  server.close(() => {\n    clearTimeout(deadline);\n    console.log('drained; the store is already on disk; exit 0');\n    process.exitCode = 0;\n  });\n  server.closeIdleConnections();\n}\nprocess.on('SIGTERM', shutdown);\nprocess.on('SIGINT', shutdown);\n",
  "scripts/load.mjs": "// Synthetic load for the planner service: `node scripts/load.mjs <base-url> [seconds]`.\n// Sends GET /tasks (and every 10th time POST /tasks) with 4 requests at a time and reports how each\n// one ended: answered (with status), refused (no connection) or broken (connection cut mid-request).\nconst [base = 'http://127.0.0.1:7330', seconds = '3'] = process.argv.slice(2);\nconst until = Date.now() + Number(seconds) * 1000;\nconst results = { answered: {}, refused: 0, broken: 0 };\nconst durations = [];\nlet n = 0;\n\nasync function worker() {\n  while (Date.now() < until) {\n    const post = ++n % 10 === 0;\n    const started = performance.now();\n    try {\n      const response = await fetch(`${base}/tasks`, post\n        ? { method: 'POST', body: JSON.stringify({ title: `Load task ${n}` }), signal: AbortSignal.timeout(5000) }\n        : { signal: AbortSignal.timeout(5000) });\n      await response.arrayBuffer();\n      results.answered[response.status] = (results.answered[response.status] ?? 0) + 1;\n      durations.push(performance.now() - started);\n    } catch (error) {\n      if (error.cause?.code === 'ECONNREFUSED') {\n        results.refused += 1;\n        await new Promise((resolve) => setTimeout(resolve, 50));\n      } else {\n        results.broken += 1;\n      }\n    }\n  }\n}\n\nawait Promise.all([worker(), worker(), worker(), worker()]);\nconst sorted = durations.toSorted((a, b) => a - b);\nconst at = (p) => (sorted.length ? sorted[Math.ceil((p / 100) * sorted.length) - 1].toFixed(1) : '-');\nconsole.log(`answered ${JSON.stringify(results.answered)}, refused ${results.refused}, broken ${results.broken}; p50 ${at(50)} ms, p95 ${at(95)} ms`);\n",
  "test/app.test.ts": "// Real-HTTP tests of the planner API, each with its own temp data directory.\nimport assert from 'node:assert/strict';\nimport { mkdtemp, rm } from 'node:fs/promises';\nimport { tmpdir } from 'node:os';\nimport path from 'node:path';\nimport { test } from 'node:test';\nimport { createApp, type Health } from '../src/app.ts';\nimport { openStore } from '../src/store.ts';\n\nasync function start(t: { after(fn: () => unknown): void }, health: Health = { shuttingDown: false }) {\n  const dir = await mkdtemp(path.join(tmpdir(), 'no12-lab-'));\n  const server = createApp(await openStore(dir), health);\n  await new Promise<void>((resolve) => server.listen(0, '127.0.0.1', resolve));\n  t.after(async () => {\n    server.close();\n    await rm(dir, { recursive: true, force: true });\n  });\n  const { port } = server.address() as { port: number };\n  return `http://127.0.0.1:${port}`;\n}\n\ntest('GET /tasks lists high priority first', async (t) => {\n  const base = await start(t);\n  const tasks = await (await fetch(`${base}/tasks`)).json();\n  assert.deepEqual(tasks.map((task: { id: string }) => task.id), ['t-04', 't-02', 't-01', 't-03']);\n});\n\ntest('POST /tasks stores a task', async (t) => {\n  const base = await start(t);\n  const response = await fetch(`${base}/tasks`, { method: 'POST', body: JSON.stringify({ title: '%%dentist%%', priority: 'normal' }) });\n  assert.equal(response.status, 201);\n  const tasks = await (await fetch(`${base}/tasks`)).json();\n  assert.equal(tasks.length, 5);\n});\n\ntest('GET /readyz answers 503 while shutting down, /livez stays 200', async (t) => {\n  const health = { shuttingDown: false };\n  const base = await start(t, health);\n  assert.equal((await fetch(`${base}/readyz`)).status, 200);\n  health.shuttingDown = true;\n  assert.equal((await fetch(`${base}/readyz`)).status, 503);\n  assert.equal((await fetch(`${base}/livez`)).status, 200);\n});\n\ntest('GET /metrics counts requests per route and status', async (t) => {\n  const base = await start(t);\n  await fetch(`${base}/tasks`);\n  await fetch(`${base}/tasks`);\n  const text = await (await fetch(`${base}/metrics`)).text();\n  assert.match(text, /http_requests_total\\{route=\"\\/tasks\",status=\"200\"\\} 2/);\n  assert.match(text, /http_request_duration_ms\\{route=\"\\/tasks\",quantile=\"0.95\"\\} \\d/);\n});\n"
};

const pkg = JSON.parse(readFileSync('package.json', 'utf8'));
const dirty = execSync('git status --porcelain', { encoding: 'utf8' }).trim();
if (pkg.name !== 'no12-lab' || pkg.version !== '1.3.0') {
  console.error(`This is ${pkg.name} ${pkg.version}, not no12-lab 1.3.0; nothing was changed.`);
  process.exitCode = 1;
} else if (dirty) {
  console.error(`Commit or undo these changes first; nothing was changed:\n${dirty}`);
  process.exitCode = 1;
} else {
  for (const [name, text] of Object.entries(files)) writeFileSync(name, text);
  pkg.version = '1.4.0';
  writeFileSync('package.json', JSON.stringify(pkg, null, 2) + '\n');
  console.log(`Upgraded no12-lab to 1.4.0: ${Object.keys(files).join(', ')}, package.json`);
}
